---
title: "Day1"
execute:
  freeze: true
format:
  html:
    code-tools: true
---


Here is some text, to introduce the subject of the day

<div>

```{=html}
<iframe class="slide-deck" src="slides/template/"></iframe>
```

</div>

# Worked examples and activities

## Resampling

```{r eval=FALSE}
# Set seed
set.seed(42) # The answer !

# Basic objects
predVal <- 0:5000 # A value of 5000 m was used as extreme elevation to define the limit. If a threshold was not reach after reaching this elevation, it was considered that the underlying model was too extreme

nboot <- 1000

# Result object
bootModel <- array(NA, dim = c(length(predVal), nboot, length(xBase)))

# Resample model parameters and calculate model predictions
for(i in 1:length(xBase)){
  # Model parameters used for the resampling
  paramMean <- summary(modelTrans[[1]])$coefficients[,1]
  paramCov <- summary(modelTrans[[1]])$cov.unscaled
 
  # Resample model parameters
  paramSmpl <- MASS::mvrnorm(nboot, paramMean, paramCov)
 
  # Calculate model predictions using the resampled model parameters
  for(j in 1:nboot){
    bootModel[,j,i] <- binomial(link = "logit")$linkinv(paramSmpl[j,1] +
                                                        paramSmpl[j,2] * predVal)
  }
}
```

## Plot one model

```{r eval=FALSE}
plot(expla,
     acsa,
     pch = 19,
     cex = pointCode$count/4,
     xlab = "Gradient",
     ylab = "Species occurrences",
     xaxt = "n",
     yaxt = "n",
     cex.lab = 1.5)

axis(2,
     at = c(0, 1),
     las = 1,
     cex.axis = 1.25)

for(i in 1:nboot){
  lines(bootModel[1:1001,i,1], col = rgb(0,0,1, 0.05))
}
```