---
title: "Course content"
---

[Daily schedule](topics/schedule)

[Link to Shared notes document](https://docs.google.com/document/d/1JkJVr9EKcXTqCQgHTCtxxwEV0M64JDt7icbv9FsPw-s/edit?tab=t.0)

## Day 1: Introduction, data simulation, discrete models

[Course Syllabus](PlanDeCoursBIO709.pdf)

:::: {.columns}

::: {.column width="50%"}

### Theory

* [Introduction to the course and location](slides/00_Introduction)
* [Data we'll be using](slides/01_Data)
* [Probability Distributions](slides/02_5_Distribution)

:::

::: {.column width="50%"}

### Exercices 

* [Catch a wild Distribution](topics/00_distributions)

:::

::::

:::{.callout-important}
### Monday night Stan installation session! 
To use Stan in R, the `rstan` R package is needed. To install it, follow the steps [in this vignette](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started). Make sure you can run the example in the **Verifying Installation**

If you have not yet managed to install Stan and `rstan`, I will be available on **Monday evening**. From Tuesday onwards we won't have time to pause to fix installation issues!
:::

## Day 2: Linear Regression and Introduction to Stan

:::: {.columns}

::: {.column width="50%"}
### Theory

* [Linear models](slides/04_Linear_model)
* [Bayesian and MCMC](slides/02_Bayesian)

:::

::: {.column width="50%"}
### Exercises
* [Simulation and model fitting in Stan](topics/01_simulation)
:::

::::

## Day 3: Simple hierarchical models

:::: {.columns}

::: {.column width="50%"}

### Theory

* [Simple hierarchical models](slides/06_Simple_hierarchical_model)

:::

::: {.column width="50%"}
### Exercises

* [Discrete predictors](topics/discrete_predictor)
* [Linear regression](topics/02_regression)

:::

::::



## Day 4: Advanced hierarchical models

:::: {.columns}

::: {.column width="50%"}
### Theory

* [Complex hierarchical models](slides/08_Complex_hierarchical_model)

:::

::: {.column width="50%"}
### Exercises

* [Hierarchy on the intercept](topics/03_one_random_effect)
* [Hierarchy on the slope](topics/correlated_effects)
:::

::::


## Day 5: Constrained models: Gaussian processes

:::: {.columns}

::: {.column width="50%"}
### Theory

* [Convergence trick](slides/07_Convergence_trick)
* [Gaussian process](slides/09_Gaussian_process)

:::

::: {.column width="50%"}
### Exercises

* [Intercept-Only Model](topics/intercept_only)
* [Gaussian process](topics/04_gp)
:::

::::

## Extra{.hidden}

* [Phylogeny](topics/04-phylo)

