<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Guillaume Blanchet – Andrew MacDonald – Vincent Tolon">
<meta name="dcterms.date" content="2023-05-09">

<title>Modèles hiérarchiques pour les sciences de la vie - Linear models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Modèles hiérarchiques pour les sciences de la vie</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">
 <span class="menu-text">Advanced Statistics and hierarchical models</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#basic-regression-model" id="toc-basic-regression-model" class="nav-link active" data-scroll-target="#basic-regression-model">Basic regression model</a></li>
  <li><a href="#basic-regression-model-1" id="toc-basic-regression-model-1" class="nav-link" data-scroll-target="#basic-regression-model-1">Basic regression model</a></li>
  <li><a href="#basic-regression-model-2" id="toc-basic-regression-model-2" class="nav-link" data-scroll-target="#basic-regression-model-2">Basic regression model</a></li>
  <li><a href="#estimating-regression-parameters" id="toc-estimating-regression-parameters" class="nav-link" data-scroll-target="#estimating-regression-parameters">Estimating regression parameters</a></li>
  <li><a href="#estimating-regression-parameters-1" id="toc-estimating-regression-parameters-1" class="nav-link" data-scroll-target="#estimating-regression-parameters-1">Estimating regression parameters</a>
  <ul class="collapse">
  <li><a href="#models-results" id="toc-models-results" class="nav-link" data-scroll-target="#models-results">Model’s results</a></li>
  </ul></li>
  <li><a href="#estimating-regression-parameters-2" id="toc-estimating-regression-parameters-2" class="nav-link" data-scroll-target="#estimating-regression-parameters-2">Estimating regression parameters</a>
  <ul class="collapse">
  <li><a href="#sampling-model-parameters" id="toc-sampling-model-parameters" class="nav-link" data-scroll-target="#sampling-model-parameters">Sampling model parameters</a></li>
  </ul></li>
  <li><a href="#estimating-regression-parameters-3" id="toc-estimating-regression-parameters-3" class="nav-link" data-scroll-target="#estimating-regression-parameters-3">Estimating regression parameters</a>
  <ul class="collapse">
  <li><a href="#sampling-model-parameters-1" id="toc-sampling-model-parameters-1" class="nav-link" data-scroll-target="#sampling-model-parameters-1">Sampling model parameters</a></li>
  </ul></li>
  <li><a href="#estimating-regression-parameters-4" id="toc-estimating-regression-parameters-4" class="nav-link" data-scroll-target="#estimating-regression-parameters-4">Estimating regression parameters</a>
  <ul class="collapse">
  <li><a href="#sampling-model-parameters-2" id="toc-sampling-model-parameters-2" class="nav-link" data-scroll-target="#sampling-model-parameters-2">Sampling model parameters</a></li>
  </ul></li>
  <li><a href="#estimating-regression-parameters-5" id="toc-estimating-regression-parameters-5" class="nav-link" data-scroll-target="#estimating-regression-parameters-5">Estimating regression parameters</a>
  <ul class="collapse">
  <li><a href="#sampling-model-parameters-3" id="toc-sampling-model-parameters-3" class="nav-link" data-scroll-target="#sampling-model-parameters-3">Sampling model parameters</a></li>
  </ul></li>
  <li><a href="#estimating-regression-parameters-6" id="toc-estimating-regression-parameters-6" class="nav-link" data-scroll-target="#estimating-regression-parameters-6">Estimating regression parameters</a>
  <ul class="collapse">
  <li><a href="#sampling-model-parameters-4" id="toc-sampling-model-parameters-4" class="nav-link" data-scroll-target="#sampling-model-parameters-4">Sampling model parameters</a></li>
  </ul></li>
  <li><a href="#estimating-regression-parameters-7" id="toc-estimating-regression-parameters-7" class="nav-link" data-scroll-target="#estimating-regression-parameters-7">Estimating regression parameters</a>
  <ul class="collapse">
  <li><a href="#sampling-model-parameters-5" id="toc-sampling-model-parameters-5" class="nav-link" data-scroll-target="#sampling-model-parameters-5">Sampling model parameters</a></li>
  </ul></li>
  <li><a href="#estimating-regression-parameters-8" id="toc-estimating-regression-parameters-8" class="nav-link" data-scroll-target="#estimating-regression-parameters-8">Estimating regression parameters</a>
  <ul class="collapse">
  <li><a href="#sampling-model-parameters-6" id="toc-sampling-model-parameters-6" class="nav-link" data-scroll-target="#sampling-model-parameters-6">Sampling model parameters</a></li>
  </ul></li>
  <li><a href="#estimating-regression-parameters-9" id="toc-estimating-regression-parameters-9" class="nav-link" data-scroll-target="#estimating-regression-parameters-9">Estimating regression parameters</a>
  <ul class="collapse">
  <li><a href="#sampling-model-parameters-7" id="toc-sampling-model-parameters-7" class="nav-link" data-scroll-target="#sampling-model-parameters-7">Sampling model parameters</a></li>
  </ul></li>
  <li><a href="#estimating-regression-parameters-10" id="toc-estimating-regression-parameters-10" class="nav-link" data-scroll-target="#estimating-regression-parameters-10">Estimating regression parameters</a>
  <ul class="collapse">
  <li><a href="#sampling-model-parameters-8" id="toc-sampling-model-parameters-8" class="nav-link" data-scroll-target="#sampling-model-parameters-8">Sampling model parameters</a></li>
  </ul></li>
  <li><a href="#estimating-regression-parameters-11" id="toc-estimating-regression-parameters-11" class="nav-link" data-scroll-target="#estimating-regression-parameters-11">Estimating regression parameters</a>
  <ul class="collapse">
  <li><a href="#sampling-model-parameters-9" id="toc-sampling-model-parameters-9" class="nav-link" data-scroll-target="#sampling-model-parameters-9">Sampling model parameters</a></li>
  </ul></li>
  <li><a href="#estimating-regression-parameters-12" id="toc-estimating-regression-parameters-12" class="nav-link" data-scroll-target="#estimating-regression-parameters-12">Estimating regression parameters</a>
  <ul class="collapse">
  <li><a href="#sampling-model-parameters-10" id="toc-sampling-model-parameters-10" class="nav-link" data-scroll-target="#sampling-model-parameters-10">Sampling model parameters</a></li>
  </ul></li>
  <li><a href="#estimating-regression-parameters-13" id="toc-estimating-regression-parameters-13" class="nav-link" data-scroll-target="#estimating-regression-parameters-13">Estimating regression parameters</a>
  <ul class="collapse">
  <li><a href="#sampling-model-parameters-11" id="toc-sampling-model-parameters-11" class="nav-link" data-scroll-target="#sampling-model-parameters-11">Sampling model parameters</a></li>
  </ul></li>
  <li><a href="#estimating-regression-parameters-14" id="toc-estimating-regression-parameters-14" class="nav-link" data-scroll-target="#estimating-regression-parameters-14">Estimating regression parameters</a>
  <ul class="collapse">
  <li><a href="#sampling-model-parameters---comparison" id="toc-sampling-model-parameters---comparison" class="nav-link" data-scroll-target="#sampling-model-parameters---comparison">Sampling model parameters - Comparison</a></li>
  </ul></li>
  <li><a href="#estimating-regression-parameters-15" id="toc-estimating-regression-parameters-15" class="nav-link" data-scroll-target="#estimating-regression-parameters-15">Estimating regression parameters</a></li>
  <li><a href="#estimating-regression-parameters-16" id="toc-estimating-regression-parameters-16" class="nav-link" data-scroll-target="#estimating-regression-parameters-16">Estimating regression parameters</a></li>
  <li><a href="#estimating-regression-parameters-17" id="toc-estimating-regression-parameters-17" class="nav-link" data-scroll-target="#estimating-regression-parameters-17">Estimating regression parameters</a></li>
  <li><a href="#estimating-regression-parameters-18" id="toc-estimating-regression-parameters-18" class="nav-link" data-scroll-target="#estimating-regression-parameters-18">Estimating regression parameters</a>
  <ul class="collapse">
  <li><a href="#variance-of-the-model-sigma2" id="toc-variance-of-the-model-sigma2" class="nav-link" data-scroll-target="#variance-of-the-model-sigma2">Variance of the model (<span class="math inline">\(\sigma^2\)</span>)</a></li>
  </ul></li>
  <li><a href="#estimating-regression-parameters-19" id="toc-estimating-regression-parameters-19" class="nav-link" data-scroll-target="#estimating-regression-parameters-19">Estimating regression parameters</a>
  <ul class="collapse">
  <li><a href="#variance-of-the-model-sigma2-1" id="toc-variance-of-the-model-sigma2-1" class="nav-link" data-scroll-target="#variance-of-the-model-sigma2-1">Variance of the model (<span class="math inline">\(\sigma^2\)</span>)</a></li>
  </ul></li>
  <li><a href="#estimating-regression-parameters-20" id="toc-estimating-regression-parameters-20" class="nav-link" data-scroll-target="#estimating-regression-parameters-20">Estimating regression parameters</a>
  <ul class="collapse">
  <li><a href="#variance-of-the-model-sigma2-2" id="toc-variance-of-the-model-sigma2-2" class="nav-link" data-scroll-target="#variance-of-the-model-sigma2-2">Variance of the model (<span class="math inline">\(\sigma^2\)</span>)</a></li>
  </ul></li>
  <li><a href="#limits-of-the-simple-linear-regression" id="toc-limits-of-the-simple-linear-regression" class="nav-link" data-scroll-target="#limits-of-the-simple-linear-regression">Limits of the simple linear regression</a></li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression">Multiple linear regression</a></li>
  <li><a href="#matrix-algebra-interlude" id="toc-matrix-algebra-interlude" class="nav-link" data-scroll-target="#matrix-algebra-interlude">Matrix algebra interlude</a>
  <ul class="collapse">
  <li><a href="#a-general-way-to-write-matrices" id="toc-a-general-way-to-write-matrices" class="nav-link" data-scroll-target="#a-general-way-to-write-matrices">A general way to write matrices</a></li>
  </ul></li>
  <li><a href="#basic-matrix-operations" id="toc-basic-matrix-operations" class="nav-link" data-scroll-target="#basic-matrix-operations">Basic matrix operations</a>
  <ul class="collapse">
  <li><a href="#the-transpose-of-a-matrix" id="toc-the-transpose-of-a-matrix" class="nav-link" data-scroll-target="#the-transpose-of-a-matrix">The transpose of a matrix</a></li>
  <li><a href="#addition-and-substraction" id="toc-addition-and-substraction" class="nav-link" data-scroll-target="#addition-and-substraction">Addition and Substraction</a></li>
  <li><a href="#multiplying-a-matrix-by-a-scalar" id="toc-multiplying-a-matrix-by-a-scalar" class="nav-link" data-scroll-target="#multiplying-a-matrix-by-a-scalar">Multiplying a matrix by a scalar</a></li>
  <li><a href="#matrix-multiplications-not-divisions" id="toc-matrix-multiplications-not-divisions" class="nav-link" data-scroll-target="#matrix-multiplications-not-divisions">Matrix multiplications (not divisions!)</a></li>
  <li><a href="#inner-product" id="toc-inner-product" class="nav-link" data-scroll-target="#inner-product">Inner product</a></li>
  </ul></li>
  <li><a href="#some-important-matrices" id="toc-some-important-matrices" class="nav-link" data-scroll-target="#some-important-matrices">Some important matrices</a>
  <ul class="collapse">
  <li><a href="#identity-matrix" id="toc-identity-matrix" class="nav-link" data-scroll-target="#identity-matrix">Identity matrix</a></li>
  <li><a href="#diagonal-matrix" id="toc-diagonal-matrix" class="nav-link" data-scroll-target="#diagonal-matrix">Diagonal matrix</a></li>
  <li><a href="#triangular-matrix" id="toc-triangular-matrix" class="nav-link" data-scroll-target="#triangular-matrix">Triangular matrix</a></li>
  <li><a href="#symmetric-matrix" id="toc-symmetric-matrix" class="nav-link" data-scroll-target="#symmetric-matrix">Symmetric matrix</a></li>
  <li><a href="#matrix-inversion" id="toc-matrix-inversion" class="nav-link" data-scroll-target="#matrix-inversion">Matrix inversion</a></li>
  <li><a href="#matrix-inversion-1" id="toc-matrix-inversion-1" class="nav-link" data-scroll-target="#matrix-inversion-1">Matrix inversion</a>
  <ul class="collapse">
  <li><a href="#inverting-a-diagonal-matrix" id="toc-inverting-a-diagonal-matrix" class="nav-link" data-scroll-target="#inverting-a-diagonal-matrix">Inverting a diagonal matrix</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#end-of-matrix-algebra-interlude" id="toc-end-of-matrix-algebra-interlude" class="nav-link" data-scroll-target="#end-of-matrix-algebra-interlude">End of matrix algebra interlude</a>
  <ul class="collapse">
  <li><a href="#multiple-linear-regression-1" id="toc-multiple-linear-regression-1" class="nav-link" data-scroll-target="#multiple-linear-regression-1">Multiple linear regression</a></li>
  <li><a href="#multiple-linear-regression-2" id="toc-multiple-linear-regression-2" class="nav-link" data-scroll-target="#multiple-linear-regression-2">Multiple linear regression</a>
  <ul class="collapse">
  <li><a href="#matrix-notation" id="toc-matrix-notation" class="nav-link" data-scroll-target="#matrix-notation">Matrix notation</a></li>
  </ul></li>
  <li><a href="#error-in-linear-models" id="toc-error-in-linear-models" class="nav-link" data-scroll-target="#error-in-linear-models">Error in linear models</a></li>
  <li><a href="#generalized-linear-models" id="toc-generalized-linear-models" class="nav-link" data-scroll-target="#generalized-linear-models">Generalized linear models</a></li>
  <li><a href="#generalized-linear-models-1" id="toc-generalized-linear-models-1" class="nav-link" data-scroll-target="#generalized-linear-models-1">Generalized linear models</a>
  <ul class="collapse">
  <li><a href="#link-functions" id="toc-link-functions" class="nav-link" data-scroll-target="#link-functions">Link functions</a></li>
  </ul></li>
  <li><a href="#generalized-linear-models-2" id="toc-generalized-linear-models-2" class="nav-link" data-scroll-target="#generalized-linear-models-2">Generalized linear models</a>
  <ul class="collapse">
  <li><a href="#link-functions-1" id="toc-link-functions-1" class="nav-link" data-scroll-target="#link-functions-1">Link functions</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Linear models</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Guillaume Blanchet – Andrew MacDonald – Vincent Tolon </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 9, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="basic-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="basic-regression-model">Basic regression model</h3>
<div style="font-size: 0.8em">
<p>Hierarchical models are a generalized version of the classic regression models you have seen in your undergraduate courses.</p>
<p>In its simplest form, a regression model is usually presented as</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_{i} + \varepsilon
\]</span></p>
<p>It is known as a <strong>simple linear model</strong>, where :</p>
<p><span class="math inline">\(y_i\)</span> is the value of a response variable for observation <span class="math inline">\(i\)</span></p>
<p><span class="math inline">\(x_i\)</span> is the value of an explanatory variable for observation <span class="math inline">\(i\)</span></p>
<p><span class="math inline">\(\beta_0\)</span> is the model intercept</p>
<p><span class="math inline">\(\beta_1\)</span> is the model slope</p>
<p><span class="math inline">\(\varepsilon\)</span> is the error term</p>
</div>
</section>
<section id="basic-regression-model-1" class="level2">
<h2 class="anchored" data-anchor-id="basic-regression-model-1">Basic regression model</h2>
<p>The cool thing about the simple linear model is that it can be studied visually quite easily.</p>
<p>For example if we are interested in knowing how a newly discovered plant species (<em>Bidonia exemplaris</em>) reacts to humidity, we can relate the biomass of <em>B. exemplaris</em> sampled at 100 sites with the soil humidity content and readily visual the data and the trend.</p>
</section>
<section id="basic-regression-model-2" class="level2">
<h2 class="anchored" data-anchor-id="basic-regression-model-2">Basic regression model</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="estimating-regression-parameters" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters">Estimating regression parameters</h2>
<p>Many techniques have been proposed to estimate the parameters of a regression model.</p>
<p>The goal of this course is not to study these techniques but we will learn how to play with the estimated parameters because it will be very useful as we move along.</p>
<p>For example, if we want to build a model’s confidence interval from a linear regression coded as</p>
<div class="cell">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(b.exemplaris <span class="sc">~</span> humidity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>How would you do it ?</strong></p>
<p>Let’s look at the model’s results are worth studying</p>
</section>
<section id="estimating-regression-parameters-1" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters-1">Estimating regression parameters</h2>
<section id="models-results" class="level3">
<h3 class="anchored" data-anchor-id="models-results">Model’s results</h3>
<div style="font-size: 0.75em">
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>(summaryReg <span class="ot">&lt;-</span> <span class="fu">summary</span>(reg))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = b.exemplaris ~ humidity)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.47988 -0.26475  0.00611  0.32590  1.36077 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2.57389    0.04720   54.53   &lt;2e-16 ***
humidity     1.10086    0.07976   13.80   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4718 on 98 degrees of freedom
Multiple R-squared:  0.6603,    Adjusted R-squared:  0.6569 
F-statistic: 190.5 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Let’s say we want to construst the model’s confidence intervals by sampling multiple times (say 100 times!) the regression parameters, which we will assume follow Gaussian distribution. How would you do this ?</p>
</div>
</section>
</section>
<section id="estimating-regression-parameters-2" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters-2">Estimating regression parameters</h2>
<section id="sampling-model-parameters" class="level3">
<h3 class="anchored" data-anchor-id="sampling-model-parameters">Sampling model parameters</h3>
<p>We could sample the model parameters but how can we do this properly ?</p>
<p><strong>Any suggestions?</strong></p>
</section>
</section>
<section id="estimating-regression-parameters-3" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters-3">Estimating regression parameters</h2>
<section id="sampling-model-parameters-1" class="level3">
<h3 class="anchored" data-anchor-id="sampling-model-parameters-1">Sampling model parameters</h3>
<p>If we look at the estimated regression model coefficient, we can learn a few things</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>summaryReg<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error  t value     Pr(&gt;|t|)
(Intercept) 2.573889 0.04720304 54.52804 4.011925e-75
humidity    1.100865 0.07975800 13.80256 1.035796e-24</code></pre>
</div>
</div>
<p>Notably, there are uncertainty around the parameters.</p>
<p>Maybe we can use this information to sample model parameters and reconstruct models across different iterations of parameters.</p>
<p>Let’s give it a shot !</p>
</section>
</section>
<section id="estimating-regression-parameters-4" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters-4">Estimating regression parameters</h2>
<section id="sampling-model-parameters-2" class="level3">
<h3 class="anchored" data-anchor-id="sampling-model-parameters-2">Sampling model parameters</h3>
<p>If we assume that the parameters of our particular model follow a Gaussian distribution, we can state that</p>
<p><span class="math display">\[\beta_0 \sim \mathcal{N}(2.574, 0.047^2)\]</span> <span class="math display">\[\beta_1 \sim \mathcal{N}(1.101, 0.080^2)\]</span></p>
</section>
</section>
<section id="estimating-regression-parameters-5" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters-5">Estimating regression parameters</h2>
<section id="sampling-model-parameters-3" class="level3">
<h3 class="anchored" data-anchor-id="sampling-model-parameters-3">Sampling model parameters</h3>
<p>In R, we can do this as follow</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Object that include regression coefficients</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>regCoef <span class="ot">&lt;-</span> summaryReg<span class="sc">$</span>coefficients</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample regression parameters</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>beta_0 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="at">mean =</span> regCoef[<span class="dv">1</span>,<span class="dv">1</span>], <span class="at">sd =</span> regCoef[<span class="dv">1</span>,<span class="dv">2</span>])</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>beta_1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="at">mean =</span> regCoef[<span class="dv">2</span>,<span class="dv">1</span>], <span class="at">sd =</span> regCoef[<span class="dv">2</span>,<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="estimating-regression-parameters-6" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters-6">Estimating regression parameters</h2>
<section id="sampling-model-parameters-4" class="level3">
<h3 class="anchored" data-anchor-id="sampling-model-parameters-4">Sampling model parameters</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="estimating-regression-parameters-7" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters-7">Estimating regression parameters</h2>
<section id="sampling-model-parameters-5" class="level3">
<h3 class="anchored" data-anchor-id="sampling-model-parameters-5">Sampling model parameters</h3>
<p>But is this the right way to do it ?</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://www.i2symbol.com/pictures/emojis/e/e/7/b/ee7b4fb9880ef3c8ee19626cdc14bf5c_384.png" class="img-fluid figure-img" style="width:20.0%"></p>
</figure>
</div>
</section>
</section>
<section id="estimating-regression-parameters-8" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters-8">Estimating regression parameters</h2>
<section id="sampling-model-parameters-6" class="level3">
<h3 class="anchored" data-anchor-id="sampling-model-parameters-6">Sampling model parameters</h3>
<p>Actually, even if the model’s confidence interval look about right, they are wrong !</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://www.i2symbol.com/pictures/emojis/8/b/f/8/8bf88079d65d540a26a1f181cf6ba060_384.png" class="img-fluid figure-img" style="width:20.0%"></p>
</figure>
</div>
</section>
</section>
<section id="estimating-regression-parameters-9" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters-9">Estimating regression parameters</h2>
<section id="sampling-model-parameters-7" class="level3">
<h3 class="anchored" data-anchor-id="sampling-model-parameters-7">Sampling model parameters</h3>
<p>The approach presented in the previous slide works only if we assume that the parameters are completely independent from one another.</p>
<p>A situation that happens only in very specific circumstances.</p>
<p>So… We need to find a way to account for the non-independencies between the parameters.</p>
<p>How can we do this ? Any ideas ?</p>
</section>
</section>
<section id="estimating-regression-parameters-10" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters-10">Estimating regression parameters</h2>
<section id="sampling-model-parameters-8" class="level3">
<h3 class="anchored" data-anchor-id="sampling-model-parameters-8">Sampling model parameters</h3>
<div style="font-size: 0.75em">
<p>Assuming that the regression parameters are normally distributed is not a bad assumption.</p>
<p>However to consider a dependencies between the parameters we need to sample them from a <strong>multivariate</strong> normal distribution where the variance of each parameter and their dependency is defined by a covariance matrix estimated specifically for the data we model.</p>
<p>The good news is that this covariance matrix is given by <code>summary.lm</code> function</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>(covReg <span class="ot">&lt;-</span> summaryReg<span class="sc">$</span>cov.unscaled)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              (Intercept)      humidity
(Intercept)  0.0100098513 -0.0005305969
humidity    -0.0005305969  0.0285782940</code></pre>
</div>
</div>
</section>
</section>
<section id="estimating-regression-parameters-11" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters-11">Estimating regression parameters</h2>
<section id="sampling-model-parameters-9" class="level3">
<h3 class="anchored" data-anchor-id="sampling-model-parameters-9">Sampling model parameters</h3>
<p>For our specific model, mathematically, we assume that</p>
<p><span class="math display">\[\begin{bmatrix}
  \beta_0\\
  \beta_1\\
\end{bmatrix} \sim \mathcal{MVN} \left( \begin{bmatrix}
  2.574\\
  1.101\\
\end{bmatrix}, \begin{bmatrix}
  0.0100 &amp; -0.0005 \\
  -0.0005 &amp; 0.0286 \\
\end{bmatrix} \right)\]</span></p>
<p><strong>Note</strong> To present the multivariate normal distribution, we rely on matrix notation. This is our first introduction into matrix algebra. We will talk about this more into this course.</p>
</section>
</section>
<section id="estimating-regression-parameters-12" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters-12">Estimating regression parameters</h2>
<section id="sampling-model-parameters-10" class="level3">
<h3 class="anchored" data-anchor-id="sampling-model-parameters-10">Sampling model parameters</h3>
<p>In R, we can sample the parameters using a multivariate normal distribution using the following code</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Object that include regression coefficients</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>regCoef <span class="ot">&lt;-</span> summaryReg<span class="sc">$</span>coefficients</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample regression parameters</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">mvrnorm</span>(<span class="dv">100</span>, regCoef[,<span class="dv">1</span>], <span class="at">Sigma =</span> covReg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="estimating-regression-parameters-13" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters-13">Estimating regression parameters</h2>
<section id="sampling-model-parameters-11" class="level3">
<h3 class="anchored" data-anchor-id="sampling-model-parameters-11">Sampling model parameters</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="estimating-regression-parameters-14" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters-14">Estimating regression parameters</h2>
<section id="sampling-model-parameters---comparison" class="level3">
<h3 class="anchored" data-anchor-id="sampling-model-parameters---comparison">Sampling model parameters - Comparison</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="1536"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="estimating-regression-parameters-15" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters-15">Estimating regression parameters</h2>
<p>So far, we focused on the most commonly assessed regression parameters of the simple linear model, the <strong>slope</strong> and the <strong>intercept</strong>, but there is another one that is very important to consider, especially for this course.</p>
<p><strong>Any ideas which one it is ?</strong></p>
</section>
<section id="estimating-regression-parameters-16" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters-16">Estimating regression parameters</h2>
<div style="font-size: 0.75em">
<p>If we go back to the mathematical description of the model</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_{i} + \varepsilon
\]</span></p>
<p>we can see that in the simple linear regression the error term (<span class="math inline">\(\varepsilon\)</span>) has actually a very precise definition:</p>
<p><span class="math display">\[\varepsilon \sim \mathcal{N}(0, \sigma^2)\]</span> where <span class="math inline">\(\sigma^2\)</span> is an estimated variance.</p>
<p>In words, it means that the error in a simple linear regression follows a Gaussian distribution with a variance that is estimated.</p>
<p>For most the course, we will play with the variance parameter <span class="math inline">\(\sigma^2\)</span> in a bunch of different ways.</p>
<p>But before we do this, we need to understand a bit more about how this parameter influence the model.</p>
</div>
</section>
<section id="estimating-regression-parameters-17" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters-17">Estimating regression parameters</h2>
<p>A first way to do this is to think about the simple linear regression in a slightly different way. Specifically, based on what we learned in the previous slide the simple linear regression can be rewritten as <span class="math display">\[
y \sim \mathcal{N}(\beta_0 + \beta_1 x_{i}, \sigma^2)
\]</span> As we will see later in this course, this writting style will become particularly useful as we move forward in this course.</p>
</section>
<section id="estimating-regression-parameters-18" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters-18">Estimating regression parameters</h2>
<section id="variance-of-the-model-sigma2" class="level3">
<h3 class="anchored" data-anchor-id="variance-of-the-model-sigma2">Variance of the model (<span class="math inline">\(\sigma^2\)</span>)</h3>
<div style="font-size: 0.75em">
<p>In essence, <span class="math inline">\(\sigma^2\)</span> tells us about what the model could not account for.</p>
<p>For example, let’s compare the biomass of <em>Bidonia exemplaris</em> with that of <em>Ilovea chicktighii</em>, another species (a carnivorous plant)</p>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-revealjs/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="1536"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="estimating-regression-parameters-19" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters-19">Estimating regression parameters</h2>
<section id="variance-of-the-model-sigma2-1" class="level3">
<h3 class="anchored" data-anchor-id="variance-of-the-model-sigma2-1">Variance of the model (<span class="math inline">\(\sigma^2\)</span>)</h3>
<p>By regressing humidity on the biomass of both plants, we can obtain the estimated parameters for each regression (which are all available using <code>summary.lm</code>)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression model</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>regBexemplaris <span class="ot">&lt;-</span> <span class="fu">lm</span>(b.exemplaris <span class="sc">~</span> humidity)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>regIchicktighii <span class="ot">&lt;-</span> <span class="fu">lm</span>(i.chicktighii <span class="sc">~</span> humidity)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>summaryRegBexemplaris <span class="ot">&lt;-</span> <span class="fu">summary</span>(regBexemplaris)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>summaryRegIchicktighii <span class="ot">&lt;-</span> <span class="fu">summary</span>(regIchicktighii)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="estimating-regression-parameters-20" class="level2">
<h2 class="anchored" data-anchor-id="estimating-regression-parameters-20">Estimating regression parameters</h2>
<section id="variance-of-the-model-sigma2-2" class="level3">
<h3 class="anchored" data-anchor-id="variance-of-the-model-sigma2-2">Variance of the model (<span class="math inline">\(\sigma^2\)</span>)</h3>
<div class="columns">
<div class="column" style="width:50%;">
<p>For <em>Bidonia exemplaris</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimated coefficients</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>summaryRegBexemplaris<span class="sc">$</span>coefficients[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error
(Intercept) 2.573889 0.04720304
humidity    1.100865 0.07975800</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimated variance</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>summaryRegBexemplaris<span class="sc">$</span>sigma</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.471798</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<p>For <em>Ilovea chicktighii</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimated coefficients</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>summaryRegIchicktighii<span class="sc">$</span>coefficients[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate  Std. Error
(Intercept) 3.991785 0.008928294
humidity    1.271250 0.015085956</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimated variance</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>summaryRegIchicktighii<span class="sc">$</span>sigma</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.089239</code></pre>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="limits-of-the-simple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="limits-of-the-simple-linear-regression">Limits of the simple linear regression</h2>
<p>There are two major pitfalls of the simple linear model for problems in the life sciences</p>
<ol type="1">
<li><p>One explanatory is almost never enough to approach biological questions nowadays.</p></li>
<li><p>The simple linear model assumes that the error follows a Gaussian distribution.</p></li>
</ol>
</section>
<section id="multiple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="multiple-linear-regression">Multiple linear regression</h2>
<div style="font-size: 0.75em">
<p>Simple linear regression can be extended to account for multiple explanatory variables to study more complexe problems. This type of regression model is known as a <strong>multiple linear regression</strong>.</p>
<p>Mathematically, a multiple linear regression can be defined as</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \dots + \beta_p x_{ip} + \varepsilon
\]</span></p>
<p>Theoretically, estimating the parameters of a multiple regression model is done the same ways as for simple linear regression. However, in practice, matrix algebra is quite practical to use in this context and also for this course in genral.</p>
<p>In this respect, let’s take a bit of time to get acquinted with different basic (and maybe not so basic!) knowledge of matrix algebra.</p>
</div>
</section>
<section id="matrix-algebra-interlude" class="level1">
<h1>Matrix algebra interlude</h1>
<section id="a-general-way-to-write-matrices" class="level2">
<h2 class="anchored" data-anchor-id="a-general-way-to-write-matrices">A general way to write matrices</h2>
<p><span class="math display">\[
\mathbf{A} = \begin{bmatrix}
                A_{11} &amp; A_{12} &amp; \dots &amp; A_{1j} &amp; \dots &amp; A_{1n}\\
                A_{21} &amp; A_{22} &amp; \dots &amp; A_{2j} &amp; \dots &amp; A_{2n}\\
                \vdots &amp; \vdots &amp; \ddots &amp; \vdots &amp; &amp; \vdots\\
              A_{i1} &amp; A_{i2} &amp; \dots &amp; A_{ij} &amp; \dots &amp; A_{in}\\
            \vdots &amp; \vdots &amp; &amp; \vdots &amp; \ddots &amp; \vdots\\
            A_{m1} &amp; A_{m2} &amp; \dots &amp; A_{mj} &amp; \dots &amp; A_{mn}\\
        \end{bmatrix}
\]</span> <span class="math display">\[A = \left[a_{ij}\right]=\left[a_{ij}\right]_{m\times n}\]</span></p>
</section>
</section>
<section id="basic-matrix-operations" class="level1">
<h1>Basic matrix operations</h1>
<section id="the-transpose-of-a-matrix" class="level2">
<h2 class="anchored" data-anchor-id="the-transpose-of-a-matrix">The transpose of a matrix</h2>
<div style="font-size: 0.65em">
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="math display">\[A = \begin{bmatrix}
          5 &amp; -6 &amp; 4 &amp; -4\\
        \end{bmatrix}
\]</span></p>
<p><span class="math display">\[B = \begin{bmatrix}
          -8\\
          9\\
          -2\\
        \end{bmatrix}
\]</span></p>
<p><span class="math display">\[C = \begin{bmatrix}
          -4 &amp; 1\\
          2 &amp; -5\\
        \end{bmatrix}
\]</span></p>
</div><div class="column" style="width:50%;">
<p><span class="math display">\[A^t=\begin{bmatrix}
          5\\
          -6\\
          4\\
          -4\\
        \end{bmatrix}
\]</span></p>
<p><span class="math display">\[B^t =\begin{bmatrix}
          -8 &amp; 9 &amp; -2\\
        \end{bmatrix}
\]</span></p>
<p><span class="math display">\[C^t =\begin{bmatrix}
          -4 &amp; 2\\
          1 &amp; -5\\
        \end{bmatrix}
\]</span></p>
</div>
</div>
<p>In R</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="sc">-</span><span class="dv">2</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>A</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,]    3    5
[2,]    1   -2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>(A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,]    3    1
[2,]    5   -2</code></pre>
</div>
</div>
</div>
</section>
<section id="addition-and-substraction" class="level2">
<h2 class="anchored" data-anchor-id="addition-and-substraction">Addition and Substraction</h2>
<p><span class="math display">\[\mathbf{C} = \mathbf{A}\pm \mathbf{B}\]</span> <span class="math display">\[C_{ij} = A_{ij} \pm B_{ij}\]</span></p>
<div style="color: blue;">
<p><span class="math display">\[\begin{bmatrix}
                3 &amp; 5\\
                1 &amp; -2\\
            \end{bmatrix} +
            \begin{bmatrix}
                2 &amp; 1\\
                4 &amp; -2\\
            \end{bmatrix} =
            \begin{bmatrix}
                3+2 &amp; 5+1\\
                1+4 &amp; -2-2\\
            \end{bmatrix} =
            \begin{bmatrix}
                5 &amp; 6\\
                5 &amp; -4\\
            \end{bmatrix}\]</span></p>
</div>
<p>In R</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="sc">-</span><span class="dv">2</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">2</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>A <span class="sc">+</span> B</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,]    5    6
[2,]    5   -4</code></pre>
</div>
</div>
</section>
<section id="multiplying-a-matrix-by-a-scalar" class="level2">
<h2 class="anchored" data-anchor-id="multiplying-a-matrix-by-a-scalar">Multiplying a matrix by a scalar</h2>
<p><span class="math display">\[\mathbf{B} = c\mathbf{A}\]</span> <span class="math display">\[B_{ij} = cA_{ij}\]</span></p>
<div style="color: blue;">
<p><span class="math display">\[
            0.3 \begin{bmatrix}
                3 &amp; 5\\
                1 &amp; -2\\
            \end{bmatrix} =  
            \begin{bmatrix}
                0.9 &amp; 1.5\\
                0.3 &amp; -0.6\\
            \end{bmatrix}
\]</span></p>
</div>
<p>In R</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="sc">-</span><span class="dv">2</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>c <span class="ot">&lt;-</span> <span class="fl">0.3</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>c<span class="sc">*</span>A </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,]  0.9  1.5
[2,]  0.3 -0.6</code></pre>
</div>
</div>
</section>
<section id="matrix-multiplications-not-divisions" class="level2">
<h2 class="anchored" data-anchor-id="matrix-multiplications-not-divisions">Matrix multiplications (not divisions!)</h2>
<p><span class="math display">\[\mathbf{C} = \mathbf{A} \cdot \mathbf{B}\]</span></p>
<p><span class="math display">\[C_{ik} = \sum^{n}_{j=1}A_{ij}B_{jk}\]</span></p>
<p><strong>Rules</strong></p>
<p>Associative: <span class="math inline">\(\mathbf{A}(\mathbf{B}\mathbf{C}) = (\mathbf{A}\mathbf{B})\mathbf{C}\)</span></p>
<p>Distributive: <span class="math inline">\(\mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B}+\mathbf{A}\mathbf{C}\)</span></p>
<p>Not commutative: <span class="math inline">\(\mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A}\)</span></p>
</section>
<section id="inner-product" class="level2">
<h2 class="anchored" data-anchor-id="inner-product">Inner product</h2>
<p><span class="math display">\[(\mathbf{Ax})_i=\sum_{j=1}^{n}A_{ij}x_j\]</span></p>
<div style="color: blue;">
<p><span class="math display">\[
  \begin{bmatrix}
    3 &amp; 5\\
    1 &amp; -2\\
  \end{bmatrix}
  \begin{bmatrix}
    2\\ 5\\
  \end{bmatrix} =
  \begin{bmatrix}
    (3, 5) \cdot (2, 5)\\
    (1, -2) \cdot (2, 5) \\
  \end{bmatrix} =
  \begin{bmatrix}
    3 \times 2 + 5 \times 5\\
    1 \times 2 -2 \times 5\\
  \end{bmatrix} =
  \begin{bmatrix}
    31\\
    -8\\
  \end{bmatrix}
\]</span></p>
</div>
<p>In R</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="sc">-</span><span class="dv">2</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">5</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">1</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>A <span class="sc">%*%</span> x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1]
[1,]   31
[2,]   -8</code></pre>
</div>
</div>
</section>
</section>
<section id="some-important-matrices" class="level1">
<h1>Some important matrices</h1>
<section id="identity-matrix" class="level2">
<h2 class="anchored" data-anchor-id="identity-matrix">Identity matrix</h2>
<p>The identity matrix is a square matrix where all values of its diagonal are 0 except the diagonal values which are all 1s.</p>
<div style="font-size: 0.8em">
<div style="color: blue;">
<p><span class="math display">\[
\mathbf{I}=\begin{bmatrix}
                1 &amp; 0 &amp; 0\\
                0 &amp; 1 &amp; 0\\
                0 &amp; 0 &amp; 1\\
        \end{bmatrix}
\]</span></p>
</div>
<p>The identity matrix is important because</p>
<p><span class="math display">\[\mathbf{A} \cdot \mathbf{I}_n = \mathbf{A}\]</span> or</p>
<p><span class="math display">\[\mathbf{I}_m \cdot \mathbf{A} = \mathbf{A}\]</span></p>
</div>
</section>
<section id="diagonal-matrix" class="level2">
<h2 class="anchored" data-anchor-id="diagonal-matrix">Diagonal matrix</h2>
<p>The diagonal matrix is a square matrix where all values of its diagonal are 0 except the ones on the diagonal.</p>
<div style="font-size: 0.8em">
<p><span class="math display">\[D=
      \begin{bmatrix}
        d_1 &amp; 0 &amp; \dots &amp; 0\\
        0 &amp; d_2 &amp; \dots &amp; 0\\
        \vdots &amp; \vdots &amp; \ddots &amp; \vdots\\
        0 &amp; 0 &amp; \dots &amp; d_n\\
\end{bmatrix}\]</span></p>
<p>An example</p>
<div style="color: blue;">
<p><span class="math display">\[
\begin{bmatrix}
                -1 &amp; 0 &amp; 0\\
                0 &amp; 0 &amp; 0\\
                0 &amp; 0 &amp; 6\\
        \end{bmatrix}
\]</span></p>
</div>
</div>
</section>
<section id="triangular-matrix" class="level2">
<h2 class="anchored" data-anchor-id="triangular-matrix">Triangular matrix</h2>
<div class="columns">
<div class="column" style="width:50%;">
<section id="lower-triangular-matrix" class="level4">
<h4 class="anchored" data-anchor-id="lower-triangular-matrix">Lower triangular matrix</h4>
<p><span class="math display">\[\begin{bmatrix}
        -10 &amp; 0 &amp; 0 &amp; 0\\
        3 &amp; 0 &amp; 0 &amp; 0\\
        0 &amp; 4 &amp; 3 &amp; 0\\
        9 &amp; -5 &amp; 4 &amp; 3\\
\end{bmatrix}\]</span></p>
</section>
</div><div class="column" style="width:50%;">
<section id="upper-triangular-matrix" class="level4">
<h4 class="anchored" data-anchor-id="upper-triangular-matrix">Upper triangular matrix</h4>
<p><span class="math display">\[\begin{bmatrix}
        -10 &amp; 0 &amp; -5 &amp; 0\\
        0 &amp; 0 &amp; 5 &amp; 6\\
        0 &amp; 0 &amp; 3 &amp; 3\\
        0 &amp; 0 &amp; 0 &amp; 3\\
      \end{bmatrix}\]</span></p>
</section>
</div>
</div>
</section>
<section id="symmetric-matrix" class="level2">
<h2 class="anchored" data-anchor-id="symmetric-matrix">Symmetric matrix</h2>
<p>The values on the above and below the diagonal are match so that <span class="math inline">\(A = A^t\)</span></p>
<div style="color: blue;">
<p><span class="math display">\[
\begin{bmatrix}
                3 &amp; 4 &amp; -10\\
                4 &amp; 5 &amp; 7\\
                -10 &amp; 7 &amp; -6\\
        \end{bmatrix}
\]</span></p>
</div>
</section>
<section id="matrix-inversion" class="level2">
<h2 class="anchored" data-anchor-id="matrix-inversion">Matrix inversion</h2>
<div style="font-size: 0.8em">
<p>In matrix algebra, we cannot divide a matrix by another matrix, but we can multiple it by its inverse, which gets us to the same place. Classically, the inverse of matrix <span class="math inline">\(\mathbf{A}\)</span> is defined as <span class="math inline">\(\mathbf{A}^{-1}\)</span></p>
<p>As such, <span class="math display">\[\mathbf{A}\cdot \mathbf{A}^{-1} = \mathbf{I}\]</span> In R</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="sc">-</span><span class="dv">2</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>(Ainv <span class="ot">&lt;-</span> <span class="fu">solve</span>(A))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           [,1]       [,2]
[1,] 0.18181818  0.4545455
[2,] 0.09090909 -0.2727273</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>A <span class="sc">%*%</span> Ainv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              [,1] [,2]
[1,]  1.000000e+00    0
[2,] -2.775558e-17    1</code></pre>
</div>
</div>
</div>
</section>
<section id="matrix-inversion-1" class="level2">
<h2 class="anchored" data-anchor-id="matrix-inversion-1">Matrix inversion</h2>
<section id="inverting-a-diagonal-matrix" class="level3">
<h3 class="anchored" data-anchor-id="inverting-a-diagonal-matrix">Inverting a diagonal matrix</h3>
<p><span class="math display">\[D^{-1}=
      \begin{bmatrix}
        1/d_1 &amp; 0 &amp; \dots &amp; 0\\
        0 &amp;  1/d_2 &amp; \dots &amp; 0\\
        \vdots &amp; \vdots &amp; \ddots &amp; \vdots\\
        0 &amp; 0 &amp; \dots &amp;  1/d_n\\
\end{bmatrix}\]</span></p>
</section>
</section>
</section>
<section id="end-of-matrix-algebra-interlude" class="level1">
<h1>End of matrix algebra interlude</h1>
<section id="multiple-linear-regression-1" class="level2">
<h2 class="anchored" data-anchor-id="multiple-linear-regression-1">Multiple linear regression</h2>
<p>In this course, we will rely heavily on multiple linear regression and expand on it by studying how some of the parameters (the <span class="math inline">\(\beta\)</span>s) can depend on other other data and parameters.</p>
<p>As we saw earlier, a classic way to write multiple linear regression is</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \dots + \beta_p x_{ip} + \varepsilon
\]</span></p>
<p>However, we can rewrite this using matrix notation has</p>
<p><span class="math display">\[
\mathbf{y} = \mathbf{X}\boldsymbol{\beta} + \boldsymbol{\varepsilon}
\]</span></p>
</section>
<section id="multiple-linear-regression-2" class="level2">
<h2 class="anchored" data-anchor-id="multiple-linear-regression-2">Multiple linear regression</h2>
<section id="matrix-notation" class="level3">
<h3 class="anchored" data-anchor-id="matrix-notation">Matrix notation</h3>
<p><span class="math display">\[
\mathbf{y} = \mathbf{X}\boldsymbol{\beta} + \boldsymbol{\varepsilon}
\]</span></p>
<p>Using the matrix notation, we assume that</p>
<ul>
<li><span class="math inline">\(\mathbf{y}\)</span> is a vector of length <span class="math inline">\(n\)</span> (samples)</li>
<li><span class="math inline">\(\mathbf{X}\)</span> is a matrix with <span class="math inline">\(n\)</span> samples (rows) and representing <span class="math inline">\(p\)</span> explanatory variables (columns)</li>
<li><span class="math inline">\(\boldsymbol{\beta}\)</span> is a vector of <span class="math inline">\(p\)</span> regression coefficients</li>
<li><span class="math inline">\(\boldsymbol{\varepsilon}\)</span> is a vector of residuals of length <span class="math inline">\(n\)</span></li>
</ul>
</section>
</section>
<section id="error-in-linear-models" class="level2">
<h2 class="anchored" data-anchor-id="error-in-linear-models">Error in linear models</h2>
<p>As previously mentioned, in (simple and multiple!) linear regression the error term (<span class="math inline">\(\varepsilon\)</span>) has actually a very precise definition:</p>
<p><span class="math display">\[\varepsilon \sim \mathcal{N}(0, \sigma^2)\]</span> where <span class="math inline">\(\sigma^2\)</span> is an estimated variance</p>
<p>which means that the error linear regression follows a Gaussian distribution with an estimateed variance.</p>
<p><strong>Note</strong> The model can be written using matrix notation as<br>
<span class="math display">\[\mathbf{y} \sim \mathcal{N}(\boldsymbol{\beta}\mathbf{X}, \sigma^2)\]</span> where <span class="math inline">\(\sigma^2\)</span></p>
</section>
<section id="generalized-linear-models" class="level2">
<h2 class="anchored" data-anchor-id="generalized-linear-models">Generalized linear models</h2>
<p>To go around this problem, <em>generalized</em> linear models (GLMs) have been proposed. In essence, GLMs use <em>link functions</em> to adapt models for them to be used on non-Gaussian data.</p>
<p>Mathematically, the generic way to write generalized linear model is</p>
<p><span class="math display">\[
\widehat{y}_i = g^{-1}(\beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \dots + \beta_p x_{ip})
\]</span> or in matrix notation</p>
<p><span class="math display">\[
\widehat{\mathbf{y}} = g^{-1}(\mathbf{X}\boldsymbol{\beta})
\]</span></p>
<p>where <span class="math inline">\(g\)</span> is the link function and <span class="math inline">\(g^{-1}\)</span> the inverse link function.</p>
</section>
<section id="generalized-linear-models-1" class="level2">
<h2 class="anchored" data-anchor-id="generalized-linear-models-1">Generalized linear models</h2>
<section id="link-functions" class="level3">
<h3 class="anchored" data-anchor-id="link-functions">Link functions</h3>
<div style="font-size: 0.75em">
<p>There are many types of link functions and they are usually directly associated to the underlying data the analysis is carried out on.</p>
<p>Arguably the most common link function in ecology are</p>
<section id="logit-link-function" class="level5">
<h5 class="anchored" data-anchor-id="logit-link-function">logit link function</h5>
<p>It is commonly used for modelling binary (0-1) data.</p>
<p><span class="math display">\[
\mathbf{X}\boldsymbol{\beta} = \ln\left(\frac{\widehat{\mathbf{y}}}{1 - \widehat{\mathbf{y}}}\right)
\]</span> The inverse logit link function is</p>
<p><span class="math display">\[
\widehat{\mathbf{y}} = \frac{\exp(\mathbf{X}\boldsymbol{\beta})}{1 + \exp(\mathbf{X}\boldsymbol{\beta})} = \frac{1}{1 + \exp(-\mathbf{X}\boldsymbol{\beta})}
\]</span></p>
</section>
</div>
</section>
</section>
<section id="generalized-linear-models-2" class="level2">
<h2 class="anchored" data-anchor-id="generalized-linear-models-2">Generalized linear models</h2>
<section id="link-functions-1" class="level3">
<h3 class="anchored" data-anchor-id="link-functions-1">Link functions</h3>
<div style="font-size: 0.75em">
<p>Another commonly used link function is</p>
<section id="log-link-function" class="level5">
<h5 class="anchored" data-anchor-id="log-link-function">log link function</h5>
<p>It is commonly used for modelling count data.</p>
<p><span class="math display">\[
\mathbf{X}\boldsymbol{\beta} = \ln\left(\widehat{\mathbf{y}}\right)
\]</span> The inverse logit link function is</p>
<p><span class="math display">\[
\widehat{\mathbf{y}} = \exp(\mathbf{X}\boldsymbol{\beta})
\]</span></p>
</section>
</div>


</section>
</section>
</section>

</main> <!-- /main -->

<script>
  // htmlwidgets need to know to resize themselves when slides are shown/hidden.
  // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
  // slide changes (different for each slide format).
  (function () {
    // dispatch for htmlwidgets
    function fireSlideEnter() {
      const event = window.document.createEvent("Event");
      event.initEvent("slideenter", true, true);
      window.document.dispatchEvent(event);
    }

    function fireSlideChanged(previousSlide, currentSlide) {
      fireSlideEnter();

      // dispatch for shiny
      if (window.jQuery) {
        if (previousSlide) {
          window.jQuery(previousSlide).trigger("hidden");
        }
        if (currentSlide) {
          window.jQuery(currentSlide).trigger("shown");
        }
      }
    }

    // hookup for slidy
    if (window.w3c_slidy) {
      window.w3c_slidy.add_observer(function (slide_num) {
        // slide_num starts at position 1
        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
      });
    }

  })();
</script>

<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>